import fs from 'fs'
import os from 'os'
import { join } from 'path'

export const createCookieFile = (rawCookie: string): string | null => {
  if (!rawCookie || !rawCookie.trim()) return null

  try {
    let cookieStr = rawCookie.trim()
    if (cookieStr.startsWith('Cookie:')) {
      cookieStr = cookieStr.substring(7).trim()
    }

    const cookies = cookieStr
      .split(';')
      .map((c) => c.trim())
      .filter((c) => c)

    const lines = ['# Netscape HTTP Cookie File', '# This file is generated by my-downloader', '']

    cookies.forEach((c) => {
      const parts = c.split('=')
      if (parts.length >= 2) {
        const name = parts[0].trim()
        const value = parts.slice(1).join('=').trim()
        // 关键：写入 .bilibili.com 域
        lines.push(`.bilibili.com\tTRUE\t/\tFALSE\t2147483647\t${name}\t${value}`)
      }
    })

    const tempPath = join(os.tmpdir(), `yt-dlp-cookies-${Date.now()}.txt`)
    fs.writeFileSync(tempPath, lines.join('\n'))
    console.log('[Cookie] Temp file created:', tempPath)
    return tempPath
  } catch (err) {
    console.error('[Cookie] Failed to create file:', err)
    return null
  }
}

export const cleanupCookieFile = (path: string | null) => {
  if (path && fs.existsSync(path)) {
    try {
      fs.unlinkSync(path)
    } catch (e) {}
  }
}
